#!/bin/bash
echo -e "QA_URL=$QA_URL\nQA_USERNAME=$QA_USER_USR\nQA_PASSWORD=$QA_USER_PSW
DEVELOP_URL=$DEVELOP_URL\nDEVELOP_USERNAME=$DEVELOP_USER_USR\nDEVELOP_PASSWORD=$DEVELOP_USER_PSW
QAN_URL=$QAN_URL\nQAN_USERNAME=$QAN_USER_USR\nQAN_PASSWORD=$QAN_USER_PSW" > .env

docker build -t $1-image-$2:ver-1 .
